/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Buy new equipment to make even more electricity": "购买新设备以产生更多电力",
    "Economic Impact": "经济影响",
    "Electricty boosts electricity gain ( Don't ask me how": "电力增加电力增益（不要问我多少",
    "Employees": "员工",
    "Energy Boost": "能源提升",
    "Equipment": "设备",
    "Experts": "专家",
    "Hire employees to make more electricity": "雇用员工以产生更多电力",
    "Hire experts to boost your production": "聘请专家来提高您的产量",
    "Main": "主界面",
    "Market Pressure Vol1": "市场压力 Vol1",
    "money": "钱",
    "Refuse to sell electricity until the price goes up ( This game is slowly becoming illegal": "拒绝卖电直到价格上涨（这个游戏正在慢慢变得非法",
    "Unlock a money effect, which boosts electricty gain": "解锁金钱影响，提高电力收益",
    "Upgrades": "升级",
    "batteries": "电池",
    "Bigger Batteries": "更大的电池",
    "Buy bigger batteries": "购买更大的电池",
    "Batteries boost the money effect exponent": "电池推动金钱效应指数",
    "Battery Power": "电池力量",
    "Buying battery upgrades doesn't decrease your battery amount": "购买电池升级并不会减少您的电池电量",
    "Gain 100% of money on reset every second": "重置时每秒获得 100% 的金钱",
    "Keep money upgrades on reset": "重置时保留金钱升级",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Battery effect decreases battery cost": "电池效应降低电池成本",
    "Cost Decrease": "成本降低",
    "Batteries last longer and stock more electricity": "电池持续时间更长，储存更多电量",
    "Battery Extender": "电池扩展器",
    "Cheaper Batteries": "更便宜的电池",
    "Hire Managers": "招聘经理",
    "Hire managers to boost Employees effect": "聘请经理以提升员工效应",
    "Hire Technicians": "聘请技术员",
    "Hire technicians to boost battery effect": "聘请技术人员提高电池效果",
    "Market Pressure Vol2": "市场压力 Vol2",
    "Money effect divides battery cost at a reduced rate": "金钱效应以较低的比率划分电池成本",
    "More Upgrades": "更多升级",
    "Softcaps": "软上限",
    "Threaten to sell your electricity elsewhere if prices don't go up ( Illegal maneuvers : the return": "如果价格不上涨，则威胁要在其他地方出售电力（非法操作：回报）",
    "Unlock 3 battery upgrades": "解锁 3 次电池升级",
    "More Effects": "更多效果",
    "Cost Decrease Part 2": "成本降低第 2 部分",
    "Boost battery effect based on batteries": "基于电池的提升电池效果",
    "Battery effect reduces battery cost even more": "电池效应进一步降低电池成本",
    "Unlock the worker layer": "解锁工作层",
    "Workers": "工人",
    "Electricians": "电工",
    "Unlock a worker effect": "解锁工人效果",
    "Why Not Another Effect ?": "为什么不是另一种效果？",
    "workers": "工人",
    "Workers increase electricity gain": "工人增加电力增益",
    "Better Effect": "电池效果",
    "Triple the worker effect exponent": "三倍工人效应指数",
    "Base Booster": "基础助推器",
    "Batteries boost battery base": "电池提升电池基础",
    "Batteries boost worker gain": "电池提升工人增益",
    "Batteries cost less based on money": "电池成本更低，基于金钱",
    "Challenging": "挑战",
    "Challenges": "挑战",
    "Even More Upgrades": "更多升级",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Hardwork+": "勤奋+",
    "Hardwork": "勤奋",
    "Hardwork is more powerful and has a higher cap": "努力工作更强大，拥有更高的上限",
    "Low Demand": "需求降低",
    "Lowering Costs": "降低成本",
    "Money boosts electricity gain": "金钱增加电力收益",
    "There is a low demand of electricity, making the money gain exponent divide by 2": "电力需求低，使得货币收益指数除以2",
    "Completed": "已完成",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Batteries reset nothing": "电池什么都不重置",
    "Gain 100% of worker gain on reset every second": "每秒重置时获得 100% 的工人收益",
    "Hire Workers": "雇用工人",
    "Money boosts worker gain": "金钱促进工人收益",
    "Unlock another 3 battery upgrades": "解锁另外 3 次电池升级",
    "Unlock the first worker challenge": "解锁第一个工人挑战",
    "Worker Boost": "工人提升",
    "Workers boost battery effect": "工人提升电池效应",
    "Keep Upgrading": "不断升级",
    "Unlock yet another 5 battery upgrades": "解锁另外 5 个电池升级",
    "Batteries need maitenance, hire more workers to take care of them": "电池需要维护，雇佣更多的工人来照顾它们",
    "Maintenance": "维护",
    "New Horizons": "新视野",
    "Overcharge": "过度充电",
    "Overcharge effect also raises worker effect to the 15th power": "过度充电效果还将工人效果提高到 15 次方",
    "Overcharge your batteries, which cubes their effect": "过度充电你的电池，这会增加它们的效果",
    "Overcharge+": "过度充电+",
    "Raise Hardwork cap to 2.5": "将勤奋上限提高到 2.5",
    "Unlock a new layer": "解锁一个新层",
    "Hardwork++": "勤奋++",
    "More Challenges": "更多挑战",
    "Unlock the second worker challenge": "解锁第二个工人挑战",
    "Start": "开始",
    "Permanently unlock the buyable": "永久解锁可购买",
    "Power Outage": "电力中断",
    "There has been a power outage, which removes the battery effect, but you unlocked a buyable as replacement": "发生了停电，消除了电池效应，但您解锁了可购买的替代品",
    "Buyables": "可购买",
    "Electric Powering": "电力供应",
    "Buyable Boost": "可购买提升",
    "First money buyable's effect also reduces battery cost": "第一个金钱可购买的效果也降低了电池成本",
    "Halves the first money buyable scaling": "将第一个钱可购买的缩放比例减半",
    "Lower Scaling": "降低缩放比例",
    "Battery Booster": "电池助推器",
    "Productive Workers": "生产工人",
    "Your workers are more productive, raising their effect to the 25th power": "您的员工生产力更高，将他们的影响提高到 25 次方",
    "coal power plants": "煤炭发电厂",
    "coal power plants": "煤炭发电厂",
    "Hire more workers to take care of your coal power plants": "雇用更多工人来照顾您的燃煤电厂",
    "That Coal Ain't Burning Itself": "煤不会自己燃烧",
    "Coal power plant resets nothing": "燃煤电厂什么都不重置",
    "Coal power plant's effect also boosts worker gain": "燃煤电厂的影响也提高了工人的收益",
    "Keep battery/worker milestones and worker challenges on reset": "保留电池/工人里程碑和工人挑战重置",
    "More Power Plants = More Jobs": "更多的发电厂 = 更多的工作",
    "Unlock auto battery prestige and battery buy max": "解锁自动电池声望和电池购买最大值",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Which Are Boosting Electricity Gain By ": "哪些正在提高电力收益",
    "\t\t\t\t": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    " to battery effect base": "到电池效果基数",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Boosts electricity gain by (.+) and divides battery cost by (.+)$/, '将电力增益提高 $1 并将电池成本除以 $2'],
    [/^Boosts electricity gain by (.+)$/, '将电力增益提高 $1'],
    [/^Boost Electricty Gain By (.+)$/, '将电力增益提高 $1'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Reach (.+) workers to unlock \(You have (.+) workers$/, '达到 $1 工人即可解锁（您有 $2 工人'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Battery effect \^(.+)$/, '电池效应 \^$1'],
    [/^(.+)x And Dividing Battery Cost By (.+)x$/, '$1x 并将电池成本除以 $2x'],
    [/^Next at (.+) KWh$/, '下一个在 $1 KWh'],
    [/^Next at (.+) money$/, '下一个在 $1 钱'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Reach (.+) money to unlock \(You have (.+) money$/, '达到 $1 钱解锁（你有 $2 钱'],
	[/^([\d\.]+) batteries$/, '$1 电池'],
	[/^\/([\d\.]+)e([\d\.,]+) battery cost$/, '\/$1 电池成本'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
	[/^([\d\.]+)e([\d\.,]+) Workers$/, '$1e$2 工人'],
	[/^([\d\.]+)e([\d\.,]+) money$/, '$1e$2 钱'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) to money effect exponent$/, '$1 到金钱效果指数'],
    [/^([\d\.]+)e([\d\.,]+) workers$/, '$1e$2 工人'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Batteries$/, '$1 电池'],
    [/^([\d\.,]+) workers$/, '$1 工人'],
    [/^([\d\.,]+) money$/, '$1 钱'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Coal Power Plants$/, '$1 煤炭发电厂'],
    [/^([\d\.,]+) coal power plants$/, '$1 煤炭发电厂'],
    [/^\*([\d\.]+) to money gain$/, '\*$1 到钱增益'],
    [/^\*(.+) to worker gain$/, '\*$1 到工人增益'],
    [/^\*([\d\.]+) to electicity gain$/, '\*$1 到电力增益'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^\*(.+) to elctricity gain$/, '\*$1 到电力增益'],
    [/^\^([\d\.]+) to battery effect$/, '\^$1 到电池效果'],
    [/^\^([\d\.]+) to Employees effect$/, '\^$1 到员工效果'],
    [/^\^([\d\.]+) battery effect$/, '\^$1 电池效果'],
    [/^([\d\.]+) Batteries : Base Cost Exp (.+)$/, '$1 电池 : 基础成本经验 $2'],
    [/^Cost: (.+) coal power plants$/, '成本：$1 煤炭发电厂'],
    [/^Cost: (.+) batteries$/, '成本：$1 电池'],
    [/^Cost: (.+) money$/, '成本：$1 钱'],
    [/^Cost : (.+) money$/, '成本：$1 钱'],
    [/^Cost: (.+) workers$/, '成本：$1 工人'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Req: (.+) \/ (.+) money$/, '成本：$1 \/ $2 钱'],
    [/^Req: (.+) \/ (.+) workers$/, '成本：$1 \/ $2 工人'],
    [/^(.+) \/ (.+) money$/, '$1 \/ $2 钱'],
    [/^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+) money$/, '$1e$2 \/ $3e$4 钱'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);